### PR TITLE
add rationale to README

### PR DESCRIPTION
**Pull request by timothypratley**

### CODE REVIEW

**Comment by Chouser** [comment]
This is fantastic, I really it! I'll get the code switched over to ~@ from ...

**Comment by Chouser** [comment]
What should be the behavior of `(k. ~a b)`?  The `~a` indicates the value of `a` should be the key of a pair, which already implies the value `b` will the value of that pair. So should `~b` and `b` behave the same, or should one or the other be illegal?

**Comment by timothypratley** [comment]
> What should be the behavior of `(k. ~a b)`?

Ah yes, I like your logic. `(k. ~a b)` as a valid expression would be the kindest thing to do here. I agree with your point that `~a` (or any non-symbol key) establishes the expectation of a key-value pair, and thus that it makes sense to treat `b` as a value (similarly `(k. :k b)` should be fine) and I don't see any reason to penalize `~b` either.

Interesting to note that `(k. {a b})` seems like a reasonable thing to write as well which I think will work just fine with your existing implementation, so maybe `~` isn't really needed. 🤔 

`(k. a ~b)` is problematic because `a` will establish [:a "alpha"], leaving `~b` without a value. Perhaps an invalid arity error would be helpful in that case, or where values are expected but not present.

**Comment by timothypratley** [comment]
Oh just realized 

          `(into ~coll (mapcat identity) ~(vec xs))

Might be simpler as

          `(conj ~coll ~@xs)

As conj behaves sensibly if you give it a [kv pair] or {map of cool stuff} 🤯

**Comment by timothypratley** [comment]
Here's an implementation for `~@`:

```clojure
(defn convert-args-to-exprs [empty-coll kfn args form]
  (loop [args args
         ;; exprs will be anything that can be spread... could be a symbol, data literal or any expression
         exprs []
         ;; acc accumulates key value pairs as we encounter them
         acc empty-coll]
    (if (empty? args)
      ;; base case, we are done
      (cond-> exprs
        (seq acc) (conj acc))
      ;; analysing args
      (let [[k & more] args]
        (cond
          ;; accumulate maps until we reach an expression or the end of args
          (map? k)
          (recur more exprs (conj acc k))

          ;; stand-alone symbol: use the symbol as a keyword to make a key value pair and accumulate into acc
          (symbol? k)
          (recur more exprs (if kfn
                              (assoc acc (kfn k) k)
                              (conj acc k)))

          ;; add ~@ forms to the expression list
          (and (seq? k) (= (first k) 'clojure.core/unquote-splicing))
          (let [x (second k)]
            (if (map? x)
              (recur more exprs (conj acc x))
              (recur more
                     (cond-> exprs
                       (seq acc) (conj acc)
                       true (conj `~x))
                     empty-coll)))

          :else
          ;; regular key value pair
          (if kfn
            (if (seq more)
              ;; accumulate into acc
              (recur (rest more) exprs (assoc acc k (first more)))
              (throw (ex-info (str "No value supplied for key " (pr-str k))
                              {:id   ::keys-syntax-pairs
                               :key  k
                               :form form})))
            (recur more exprs (conj acc k))))))))

(defn restructure [empty-coll kfn args form]
  (let [exprs (convert-args-to-exprs empty-coll kfn args form)]
    (cond
      ;; there are a combination of map literals and spreads, the spreads must be done at runtime
      (next exprs)
      `(reduce into ~empty-coll ~(vec exprs))

      ;; only one expr
      (seq exprs)
      (let [x (first exprs)]
        (if (and (coll? x) (= (empty x) empty-coll))
          ;; boiled down to a singular accumulation, so return it
          x
          ;; a singular spread, ensure we always deliver something of the right type
          `(into ~empty-coll ~x)))

      ;; no exprs produces an empty map instead of nil
      ;; as this is a map constructor (like hash-map etc)
      :else
      empty-coll)))

(defmacro keys. [& args]
  (restructure {} keyword args &form))

(defmacro strs. [& args]
  (restructure {} str args &form))

(defmacro syms. [& args]
  (restructure {} #(list 'quote %) args &form))

;; Example usage:
(comment
  (let [a "alpha"
        b "beta"
        m {:x :y}
        m2 [[1 2] [3 4]]]
    #_(prn (macroexpand
           '(syms. a b 'c b {:s :t} ~@m ~@m2 :more "stuff" ~@{:k 1} ~@(map vector [:p :q :r] (range)))))
    (syms. a b 'c b {:s :t} ~@m ~@m2 :more "stuff" ~@{:k 1} ~@(map vector [:p :q :r] (range))))

  => {:q 1, :r 2, 1 2, a "alpha", :s :t, :k 1, 3 4, c "beta", :more "stuff", :x :y, :p 0, b "beta"}
  (let [a "alpha"
        b "beta"]
    (keys. a ~@(strs. b)))
  => {:a "alpha", "b" "beta"})
```

**Comment by timothypratley** [comment]
> Here's an implementation for `~@`:

Oh looks like you already implemented it 😄 nice.

**Comment by Chouser** [comment]
Rebased (with minor changes) as commit:
https://github.com/Chouser/spread/commit/1668e2e74b3503f1018cf991a0c7150cfb72381d

**Pull request closed without merging**
